petnet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from core.views import frontpage, about, frontpage2

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('about/', about, name='about'),
    path('f2/', frontpage2, name='frontpage2'),
    path('adminStore/',include('adminStore.urls')),
    path('', include('userprofile.urls')),
    path('',include('vendorsPanel.urls')),    
    path('', include('Shipping.urls')),    
    path('', include('store.urls')),
    path('', frontpage, name='frontpage'),
    
    
    
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)   
       

store/urls.py
from django.urls import path
from . import views 
urlpatterns =[

    path('categories/list/', views.Category_ListView.as_view(), name='categories_list'),
    path('categories/add/', views.Category_CreateView.as_view(), name='categories_add'),
    path('categories/<str:pk>/update/', views.Category_UpdateView.as_view(), name='categories_update'),

    
    path('search/', views.search, name="search"),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('add-item-to-order/<int:order>/<int:product_id>/',views.add_item_to_order, name='add_item_to_order'),
    path('cart/', views.cart_view, name='cart_view'),
    path('cart/checkout/',views.checkout, name="checkout"),
    path('cart/success/', views.success, name='success'),
    path('cart/success/reorder/', views.re_order, name ='re_order'),
    
    path('cart/success/reorder/item/', views.change_quantity_order, name ='re_order_item'),
    path('cart/success/reorder/delete/', views.remove_from_re_order, name ='re_order_remove'),
    path('cart/success/reorder/verify_internal/', views.verify_internal, name ='verify_internal'),
    path('cart/success/verified/', views.verified, name='verified'),
    path('cart/success/OrdersView/<int:pk>/', views.Order_DetailView.as_view(), name='order_viewCBV'),
    path('cart/success/Orders/<int:pk>/', views.order_view, name='order_view'),

    
        
    path('change-quantity/<str:product_id>', views.change_quantity, name='change_quantity'),
    path('remove-from-cart/<str:product_id>/',views.remove_from_cart, name='remove_from_cart'),
    path('<slug:slug>/', views.category_detail, name='category_detail'),
    path('<slug:category_slug>/<slug:slug>/', views.product_detail, name='product_detail'),
    
    
    
    
    
]

userprofile/urls.py
from django.contrib.auth import  views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.sigup, name='signup'),
    path('customer_signup/', views.customer_signup, name='customer_signup'),
    path('login/', auth_views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('myaccount/', views.myaccount, name='myaccount'),
    path('my-store/', views.my_store, name='my_store'),
    path('my-store/order-detail/<int:pk>/', views.MyStore_Order_DetailView.as_view(),  name="my_store_order_detail"),
    #path('my-store/order-detail/<int:pk>/', views.my_store_order_detail,  name="my_store_order_detail"),
    path('my-store/add-product/', views.add_product, name='add_product'),
    
    path('my-store/edit-product/<int:pk>/', views.ProductUpdateView.as_view(), name='edit_product'),
    path('my-store/delete-product/<int:pk>/', views.delete_product, name='delete_product'),    
    path('vendors/products/<int:pk>/', views.vendor_detail, name='vendor_detail'),    
    path('discount/', views.discount_view, name='discount_view'),
    path('editDiscount/<int:pk>/',views.EditDiscount_UpdateView.as_view(), name='editDiscount'),
    path('addDiscount/',views.AddDiscount_CreateView.as_view(), name='addDiscount'),

    
    path('check_code_name/', views.check_code_name, name='check_code_name'),
    path('customer/update/<str:pk>/', views.CustomerUpdateView.as_view(), name='stripe_CustomerUpdateView'),
    path('customer/create/<str:pk>/',views.create_customer_already_signup.as_view(),name='create_customer_already_signup'),
]

adminStore/models.py
from django.db import models
from store.models import Order, OrderItem
from django.contrib.auth.models import User


class Conversation(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE,  related_name='conversation')
    members = models.ManyToManyField(User, related_name='conversations')
    def __str__(self):
        members = ", ".join([str(member) for member in self.members.all()])
        return f"Conversation {self.id}: Order {self.order.id} with members {members}"
    
    
class Message(models.Model):
    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='received_messages')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    class Meta:
        indexes = [
            models.Index(fields=['conversation']),
            models.Index(fields=['created_at']),
            models.Index(fields=['is_read'])
        ]
        ordering = ('created_at',)
    
    def __str__(self):
        return f'{self.conversation.members}'
    
    

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files import File
from django.template.defaultfilters import slugify

from django.db.models import Sum,F

from io import BytesIO
from PIL import Image
from .validators import validate_file_extension, valid_ext_dict
from  userprofile.api_stripe import get_cupon

class Discount(models.Model):
    created_by = models.ForeignKey(User, related_name='discounts', on_delete=models.CASCADE)    
    code_name    = models.CharField(max_length=35, unique=True)
    desc    = models.TextField()
    stock   = models.IntegerField()
    times_redeemed= models.IntegerField(editable=False,blank=True,null=False,default=0)
    discount_percent = models.IntegerField()
    active  = models.BooleanField(default=False)
    created_at  = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateField(auto_now=True)
    #deleted_at = models.DateField(blank=True)

    @property
    def check_times_redeemed(self):
        times_redeemed = 0
        if self.code_name:
            times= get_cupon(self.code_name)
            if 'times_redeemed' in times[0]:
                times_redeemed = times[0]['times_redeemed']
                self.times_redeemed=times_redeemed
                if times_redeemed == self.stock:
                    self.active=False
                self.save()
        return times_redeemed
    def __str__(self):
        return f'-Code:{self.code_name} -Discount %: {self.discount_percent}'
    
    def is_valid_coupon(self,code):
        return f'VALID {code}'



class Category(models.Model):
    
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50)
    
    class Meta:
        
        verbose_name_plural = 'Categories'
        
    def __str__(self):
       return self.title

    def save(self,*args, **kwargs):
        if self.title:
            self.slug=slugify(self.title)
        return super().save(*args,**kwargs)
    
    
class Product(models.Model):
    DRAFT = 'draft'
    WAITING_APPROVAL ='waitingaproval'
    ACTIVE='active'
    DELETED='deleted'
    
    STATUS_CHOICES =(
        (DRAFT, 'Draft'),
        (WAITING_APPROVAL, 'Waiting approval'),
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted'),
    )
    
    user = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='uploads/product_images/', blank=True, null=True, validators=[validate_file_extension])
    thumbnail = models.ImageField(upload_to='uploads/product_images/thumbnail/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=ACTIVE)
    discount = models.ForeignKey(Discount, related_name='discount_id',on_delete=models.DO_NOTHING, null=True, blank=True)
    #discount = models.CharField(max_length=100,null=True, blank=True)
    id_stripe = models.CharField(max_length=100,blank=True, null=True, unique=True)
    
    class Meta:
        ordering = ('-created_at', )
        indexes = [
            models.Index(fields=['user']),
        ]
    
    def __str__(self):
        return self.title
    
    
    #overriden method for slug file
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        # print('self._state.adding---',self._state.adding)
        # print(self.thumbnail,'!= ',args)
        # print(kwargs)
        return super().save(*args, **kwargs)
        
    def get_display_price(self):
        
        for price in self.prices.all().filter(product=self):
            if price.active_price and price !=self:
                return price.price_amount/100                    
        return self.price /100
    
    
    def get_thumbnail(self):
        #print(self.thumbnail.url,' -------=====  ',self.thumbnail.field.upload_to)
        if self.thumbnail:
            origin= self.thumbnail.field.upload_to
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            else:
                return 'https://placehold.co/300x300/jpg'    
            
            
    def make_thumbnail(self, image, size=(300, 300)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)
        thumb_io = BytesIO()
        #check formats -> python -m PIL
        ext = valid_ext_dict.get(f".{image.name.split('.')[-1]}")
        
        img.save(thumb_io, ext, quality=85)
        name = image.name.replace('uploads/product_images/', '')
        thumbnail = File(thumb_io, name=name)

        return thumbnail
    

class CarouselImage(models.Model):
    product = models.ForeignKey('Product', related_name='carousel', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='carousel/')
    caption = models.CharField(max_length=100,blank=True)
    order = models.PositiveIntegerField()
    class Meta:
        ordering = ['order']

class Order(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    paid_amount = models.IntegerField(blank=True, null=True)
    is_paid = models.BooleanField(default=False)
    payment_intent = models.CharField(max_length=255)
    discount_code = models.CharField(max_length=35, null=True, blank=True)
    created_by = models.ForeignKey(User, related_name='orders', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    is_shipped = models.BooleanField(default=False)
    class Meta:
        ordering = ('-id','-created_at',)
        
    def get_display_price(self):
        return self.paid_amount /100
    
    def get_display_price_with_discount(self,user):
        if self.discount_code:
            discount,err = get_cupon(self.discount_code)
            tot_item = self.get_display_price_per_user(user)
            discount = (tot_item*100) * (discount.get('percent_off',0) /100)
            return tot_item-discount / 100
        else:
            return self.get_display_price_per_user(user)

    def __str__(self):
        return f'{self.id}'

    def get_display_price_per_user(self, user):
        total_price = self.items.filter(product__user=user).annotate(
            total_price=F('quantity') * F('price')
        ).aggregate(Sum('total_price'))['total_price__sum'] or 0
        return total_price / 100

    def get_total_quantity_per_user(self, user):
        return self.items.filter(product__user=user).aggregate(Sum('quantity'))['quantity__sum'] or 0



class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)
        
    def get_display_price(self):
        return self.price / 100
    
    def get_item_total(self):
        return (self.price/100)  * self.quantity
    
    def __str__(self) -> str:
        return f"Order: {self.order}, item:{self.product.title}"
    
    

class Product_Inventory(models.Model):
    product_id  = models.ForeignKey(Product, related_name='product_inv', on_delete=models.CASCADE)
    
    quantity    = models.IntegerField()
    created_at  = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateField(auto_now=True)
    #deleted_at = models.DateField(blank=True)
    # class Meta:        
    #     abstract =True

#this must be created with signal in orders
class Payment_Detail(models.Model):
    order_id    = models.ForeignKey(Order, related_name='payment_detail', on_delete=models.CASCADE)
    amount      = models.IntegerField()
    #provider can be another class with provider list or can be pyment type  
    provider    = models.CharField(max_length=35,blank=True)
    status      = models.CharField(max_length=10)
    created_at  = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateField(auto_now=True)

    # class Meta:
    #     abstract=True

userprofile/models.py
from email.policy import default
from pickle import TRUE
from django.db import models
from django.contrib.auth.models import Permission, User

class Userprofile(models.Model):
    user = models.OneToOneField(User, related_name='userprofile', on_delete= models.CASCADE)
    is_vendor =models.BooleanField(default=True)
    RFC = models.CharField(max_length=13,blank=True)
    def __str__(self):
        return self.user.username
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.is_vendor:
            permission = Permission.objects.get(codename='change_product')
            self.user.user_permissions.add(permission)
        else:
            permission = Permission.objects.get(codename='change_product')
            self.user.user_permissions.remove(permission)

class customerProfile(models.Model):
    stripe_cus_id = models.CharField(max_length=20, unique=True)
    user = models.OneToOneField(User, related_name='customer', on_delete=models.CASCADE)
    def __str__(self) -> str:
        return str(self.id)

userprofile/templates/userprofile/add_product.html
{% extends 'core/base.html' %}

{% block title %} {{title}} product{% endblock title %}

{% block content %}
    <h1 class="text-2xl"> {{title}} product</h1>
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="mt-6 py-4 px-8 bg-teal-500 text-white hover:bg-teal-800">Submit</button>
    </form>
    {% if title == "Edit" %}
      <a href="#" class="mt-2 inline-block py-4 px-8 bg-red-500 text-white"> Delete product</a>
    {% endif %}
{% endblock content %}

userprofile/templates/userprofile/login.html
{% extends 'core/mainBase.html' %}
{% load widget_tweaks %}


{% block title %} Login {% endblock title %}

{% block content %}
<div class="mt-6 flex justify-center">
    <h1 class="text-2xl">Login</h1>
</div>
<div class="flex justify-center">
    <div class="xl:w-5/12 lg:w-5/12 md:w-8/12 mb-12 md:mb-0">
        <form action="." method="post">
            {% csrf_token %}
            
            {% render_field form.non_field_errors %}
            <div class="row">
                <div class="mb-3">
                    {% render_field form.username.label %}
                    {% render_field form.username placeholder=form.username.label class+="form-control"  type="text" %}
                    {% render_field form.username.errors %}
                </div>
                <div class="mb-3">
                    {% render_field form.password.label %}
                    {% render_field form.password placeholder=form.password.label class+="form-control"  type="password" %}
                    
                    {% render_field form.password.errors %}
                    <input type="hidden" name="next" value="{{ next }}">
                </div>
            </div>

            <button type="submit" class="btn btn-success">Login</button>
        </form>
    </div>
</div>
<br>
<div class="row d-flex justify-content-evenly">
    <div class="col-3">
        <p>Do you want to buy ?<a href="{% url 'customer_signup' %}"><u> Register Here</u></a></p>
    </div>
    
    <div class="col-3">
        <p>Do you want to sell?<a href="{% url 'signup' %}"><u> Register Here</u></a></p>
    </div>
</div>

{% endblock content %}

userprofile/templates/userprofile/my_store.html
{% extends 'core/mainBase.html' %}

{% block title %} My account{% endblock title %}

{% block content %}

    <h1 class="text-2xl text-center"> My store</h1>
    
    
    <hr>
    <h2 class="mt-4 mb-2 text-2xl"> My Orders</h2>

    <a href="{% url 'success' %}" class="mt-4 inline-block py-4 px-8 bg-teal-500 text-white"> Success orders</a>
    <br>
    <div class="flex flex-wrap">
        <div class="w-1/5">
            <strong>Order id</strong>
        </div>
        <div class="w-1/5">
            <strong>Name</strong>
        </div>
        <div class="w-1/5">
            <strong>is paid</strong>
        </div>
        <div class="w-1/5">
            <strong>paid_amount</strong>
        </div>
        <div class="w-1/5">
            shipped
        </div>
    </div>
    {% for order_item in order_items  %}
        <div class="flex flex-wrap">
            <div class="w-1/5">
                <strong>
                    <u>
                    <a href="{% url 'my_store_order_detail' order_item.id  %}">{{order_item.id}}</a>  
                    </u>
                </strong>
            </div>
            <div class="w-1/5">
                {{order_item.first_name}} {{order_item.last_name}}
            </div>
        
            <div class="w-1/5">
                
                {% if order_item.is_paid  %}
                    Paid bill
                {% else %}
                    Not paid bill
                {% endif %}                                    
            </div>
        
            <div class="w-1/5">
                ${{order_item.get_display_price}}
            </div>
            <div class="w-1/5">
                {% if order_item.is_shipped %}
                    shipped
                {% else %}                                  
                    {% if order_item.shipping.id %}
                        <a href="{% url 'shipped_orders' order_item.shipping.id %}">
                            not shipped
                        </a>
                    {% else %}
                    {% endif %}                             
                {% endif %}
            </div>
        </div>
        <hr>
    {% endfor %}
        
    <hr>
    
    <a href="{% url 'add_product' %}" class="mt-6 inline-block py-4 px-8 bg-teal-500 text-white">Add product</a>
    
    <h2 class="mt-6 text-xl">My products</h2>
    
    {% if products %}
        <div class="flex flex-wrap ">
            {%for product in products %}
                <div class="product w-1/3 p-2">
                    <div class=" p-4 bg-gray-100">
                        <a href="{% url 'edit_product' product.id %}">
                            {% if product.image %}
                                <div class="image mb-2">
                                    <img width="30%" class="object-scale-down" src="{{product.get_thumbnail}}" alt="Image of {{product.title}}">
                                </div>
                            {% endif %}
                            <h2 class="text-xl">{{product.title}}</h2>
                            <p class="text-xs text-grey-600">$ {{product.get_display_price}}</p>
                            
                            <hr class="my-3">

                            <p><strong>Status: {{product.get_status_display}}</strong></p>
                        </a>
                    </div>                
                </div>
            {% endfor %}
        </div>
    {% else %} 
        <p class="mt-6 py-4 px-8 bg-gray-200">You don't have any products yet</p>
    {% endif %}
    
<hr>
<br>

<a href="{% url 'discount_view' %}" class="mt-6 inline-block py-4 px-8 bg-teal-500 text-white">Add Discount code</a>
{% include 'userprofile/inventory/partial_discount.html' %}
<br>

{% endblock content %}


{% block scripts %}
    <script>
        function reset_stock(stock,id_code){
            let ele = document.getElementById(`id_${id_code}`)
            if(parseInt(stock)>0){
                
                if (confirm("there is redeemed code for this coupon, edit this will reset the redeem count to cero, are you sure?")){                    
                    ele.click()
                }
            }else{ele.click()}
        }
    </script>
{% endblock scripts %}

userprofile/templates/userprofile/my_store2.html
{% extends 'core/mainBase.html' %}

{% block title %} My account{% endblock title %}

{% block content %}

    <h1 class="text-2xl text-center">My Store</h1>
    <hr>
    <h2 class="mt-4 mb-2 text-2xl">My Orders</h2>

    <a href="{% url 'success' %}" class="mt-4 btn btn-primary">Success Orders</a>
    <br>
    <div class="row mt-4">
        <div class="col-md-2"><strong>Order id</strong></div>
        <div class="col-md-2"><strong>Name</strong></div>
        <div class="col-md-2"><strong>Is Paid</strong></div>
        <div class="col-md-2"><strong>Paid Amount</strong></div>
        <div class="col-md-2"><strong>Shipped</strong></div>
    </div>

    {% for order_item in orders  %}
        <div class="row mt-2">
            <div class="col-md-2">
                <strong>
                    <u>
                    <a href="{% url 'my_store_order_detail' order_item.id  %}">{{order_item.id}}</a>  
                    </u>
                </strong>
            </div>
            <div class="col-md-2">{{order_item.first_name}} {{order_item.last_name}}</div>
        
            <div class="col-md-2">
                {% if order_item.is_paid  %}
                    Paid bill
                {% else %}
                    Not paid bill
                {% endif %}                                    
            </div>
        
            <div class="col-md-2">
                ${{order_item.get_display_price}}
            </div>
            <div class="col-md-2">
                {% if order_item.is_shipped %}
                    Shipped
                {% else %}                                  
                    {% if order_item.shipping.id %}
                        <a href="{% url 'shipped_orders' order_item.shipping.id %}">
                            Not Shipped
                        </a>
                    {% else %}
                    {% endif %}                             
                {% endif %}
            </div>
        </div>
        <hr>
    {% endfor %}        
    <hr>




    <!--PRODUCT-->
    <h2 class="mt-6 text-xl">My Products</h2>
    <a href="{% url 'add_product' %}" class="mt-6 btn btn-primary">Add Product</a>
    {% if products %}
        <div class="row mt-4">
            {% for product in products %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        {% if product.image %}
                            <img class="card-img-top" src="{{product.get_thumbnail}}" alt="Image of {{product.title}}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{product.title}}</h5>
                            <p class="card-text">$ {{product.get_display_price}}</p>
                            <hr>
                            <p class="card-text"><strong>Status:</strong> {{product.get_status_display}}</p>
                            <a href="{% url 'edit_product' product.id %}" class="btn btn-primary">Edit Product</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p class="mt-6 py-4 px-8 bg-gray-200">You don't have any products yet</p>
    {% endif %}
    
    <hr>


<!--DISCOUNTS-->

{% include 'userprofile/inventory/partial_discount.html' %}
{% endblock content %}

{% block scripts %}
    <script>
        function reset_stock(stock,id_code){
            let ele = document.getElementById(`id_${id_code}`)
            if(parseInt(stock)>0){
                
                if (confirm("there is redeemed code for this coupon, edit this will reset the redeem count to cero, are you sure?")){                    
                    ele.click()
                }
            }else{ele.click()}
        }
    </script>
{% endblock scripts %}

userprofile/templates/userprofile/myaccount.html
{% extends 'core/mainBase.html' %}

{% block title %} My account{% endblock title %}

{% block content %}


    <h1 class="text-2xl"> <strong>{{request.user}}'s</strong> account </h1>
    <button type="button" class="btn btn-primary" data-bs-toggle="collapse" data-bs-target="#collapseExample">
        Show account Info
    </button>

    <div class="collapse" id="collapseExample">
        <div class="card card-body">
            <form action="." method="post"  class="space-y-5">
                {% csrf_token %}
                {{form.as_p}}
                {{customer_form.country.label}}
                <select name="country" id="country-select" class="form-control">
                    <option value="">-- Select a country --</option>
                  </select>
                {{customer_form.as_p}}
                <button class="mt-6 py-4 px-8 btn btn-success">Submit</button>
            </form>
        </div>
    </div>


{% endblock content%}


{% block scripts %}

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const countrySelect = document.getElementById('country-select');
            const countryInput = document.getElementById('id_country');
            const countryLabel = document.querySelector('label[for="id_country"]');
            countryLabel.setAttribute('hidden', '');
            countryInput.setAttribute('hidden', '');
        
            // fetch list of countries
            fetch('https://restcountries.com/v2/all')
              .then(response => response.json())
              .then(data => {
                // generate options for country select element
                const options = data.map(country => {
                  return `<option value="${country.alpha2Code}">${country.name}</option>`
                })
                // add options to country select element
                countrySelect.innerHTML += options.join('');
        
                // check if country input has valid value and select it in country select
                if (/^[A-Za-z]{2}$/.test(countryInput.value)) {
                  const countryCode = countryInput.value.toUpperCase();
                  countrySelect.value = countryCode;
                }
              })
              .catch(error => {
                console.error(error)
              })
        
            // add event listener to country select element
            countrySelect.addEventListener('change', () => {
              countryInput.value = countrySelect.value; // update country input value
            })
          })
        
    </script>

{% endblock scripts %}

userprofile/templates/userprofile/product_form.html
{% extends 'core/mainBase.html' %}

{% block title %} {{title}} product{% endblock title %}

{% block content %}
    <h1 class="text-2xl"> {{title}} product</h1>
    <figure class="img-fluid" style="width: 20%;" >
      <img src="{{ product.get_thumbnail }}" alt="">
    </figure>
    <form action="." method="post" enctype="multipart/form-data" class="space-y-5">
        {% csrf_token %}
        {% for field in form %}
        {% if field.errors %}
            <div class="error">
                <ul>
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% endfor %}
        {{form.category}}
        {{form.title}}
        {{form.description}}
        
        <div class="row">
          <div class="col-2">{{form.price}}$ <span id="display-price"></span></div>
          
        </div>
        
        <hr>
        <br>
        <br>
        
        {{form.image.label}}
        {{form.image}}
        {{form.status}}
        {{form.discount}}
        {{form.id_stripe}}
        <hr>
        <h2>Extra Images</h2>  
        {% for form in carouselFormSet %}
          <div style="padding: 10px;">
            {{ form.image }}
            <div style="border-bottom: 1px solid black;">
              {{ form.caption }}
            </div>
          </div>
        {% endfor %}
        {{ carouselFormSet.non_form_errors }}
        {{ carouselFormSet.management_form }}

        
        <button class="btn btn-success">Submit</button>
    </form>
    {% if product %}
      <a href="{% url 'delete_product' product.id %}" class="mt-2 inline-block py-4 px-8 bg-red-500 text-white"> Delete product</a>
    {% endif %}
{% endblock content %}


{% block scripts %}
<script>
  const form = document.querySelector('form');
  const priceInput = document.querySelector('#id_price');
  const displayPrice = document.querySelector('#display-price');
  window.addEventListener('load', function() {
      displayPrice.textContent = (priceInput.value / 100).toFixed(2);
  });

  priceInput.addEventListener('input', function() {
    displayPrice.textContent = (priceInput.value / 100).toFixed(2);
    
  });
</script>
{% endblock scripts %}