petnet/urls.py
from django.conf import settings
from django.conf.urls.static import static
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from core.views import frontpage, about, frontpage2

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('about/', about, name='about'),
    path('f2/', frontpage2, name='frontpage2'),
    path('adminStore/',include('adminStore.urls')),
    path('', include('userprofile.urls')),
    path('',include('vendorsPanel.urls')),    
    path('', include('Shipping.urls')),    
    path('', include('store.urls')),
    path('', frontpage, name='frontpage'),
    
    
    
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)   
       

store/urls.py
from django.urls import path
from . import views 
urlpatterns =[

    path('categories/list/', views.Category_ListView.as_view(), name='categories_list'),
    path('categories/add/', views.Category_CreateView.as_view(), name='categories_add'),
    path('categories/<str:pk>/update/', views.Category_UpdateView.as_view(), name='categories_update'),

    
    path('search/', views.search, name="search"),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('add-item-to-order/<int:order>/<int:product_id>/',views.add_item_to_order, name='add_item_to_order'),
    path('cart/', views.cart_view, name='cart_view'),
    path('cart/checkout/',views.checkout, name="checkout"),
    path('cart/success/', views.success, name='success'),
    path('cart/success/reorder/', views.re_order, name ='re_order'),
    
    path('cart/success/reorder/item/', views.change_quantity_order, name ='re_order_item'),
    path('cart/success/reorder/delete/', views.remove_from_re_order, name ='re_order_remove'),
    path('cart/success/reorder/verify_internal/', views.verify_internal, name ='verify_internal'),
    path('cart/success/verified/', views.verified, name='verified'),
    path('cart/success/OrdersView/<int:pk>/', views.Order_DetailView.as_view(), name='order_viewCBV'),
    path('cart/success/Orders/<int:pk>/', views.order_view, name='order_view'),

    
        
    path('change-quantity/<str:product_id>', views.change_quantity, name='change_quantity'),
    path('remove-from-cart/<str:product_id>/',views.remove_from_cart, name='remove_from_cart'),
    path('<slug:slug>/', views.category_detail, name='category_detail'),
    path('<slug:category_slug>/<slug:slug>/', views.product_detail, name='product_detail'),
    
    
    
    
    
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files import File
from django.template.defaultfilters import slugify

from django.db.models import Sum,F

from io import BytesIO
from PIL import Image
from .validators import validate_file_extension, valid_ext_dict
from  userprofile.api_stripe import get_cupon

class Discount(models.Model):
    created_by = models.ForeignKey(User, related_name='discounts', on_delete=models.CASCADE)    
    code_name    = models.CharField(max_length=35, unique=True)
    desc    = models.TextField()
    stock   = models.IntegerField()
    times_redeemed= models.IntegerField(editable=False,blank=True,null=False,default=0)
    discount_percent = models.IntegerField()
    active  = models.BooleanField(default=False)
    created_at  = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateField(auto_now=True)
    #deleted_at = models.DateField(blank=True)

    @property
    def check_times_redeemed(self):
        times_redeemed = 0
        if self.code_name:
            times= get_cupon(self.code_name)
            if 'times_redeemed' in times[0]:
                times_redeemed = times[0]['times_redeemed']
                self.times_redeemed=times_redeemed
                if times_redeemed == self.stock:
                    self.active=False
                self.save()
        return times_redeemed
    def __str__(self):
        return f'-Code:{self.code_name} -Discount %: {self.discount_percent}'
    
    def is_valid_coupon(self,code):
        return f'VALID {code}'



class Category(models.Model):
    
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50)
    
    class Meta:
        
        verbose_name_plural = 'Categories'
        
    def __str__(self):
       return self.title

    def save(self,*args, **kwargs):
        if self.title:
            self.slug=slugify(self.title)
        return super().save(*args,**kwargs)
    
    
class Product(models.Model):
    DRAFT = 'draft'
    WAITING_APPROVAL ='waitingaproval'
    ACTIVE='active'
    DELETED='deleted'
    
    STATUS_CHOICES =(
        (DRAFT, 'Draft'),
        (WAITING_APPROVAL, 'Waiting approval'),
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted'),
    )
    
    user = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, blank=True)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='uploads/product_images/', blank=True, null=True, validators=[validate_file_extension])
    thumbnail = models.ImageField(upload_to='uploads/product_images/thumbnail/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=ACTIVE)
    discount = models.ForeignKey(Discount, related_name='discount_id',on_delete=models.DO_NOTHING, null=True, blank=True)
    #discount = models.CharField(max_length=100,null=True, blank=True)
    id_stripe = models.CharField(max_length=100,blank=True, null=True, unique=True)
    
    class Meta:
        ordering = ('-created_at', )
        indexes = [
            models.Index(fields=['user']),
        ]
    
    def __str__(self):
        return self.title
    
    
    #overriden method for slug file
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        # print('self._state.adding---',self._state.adding)
        # print(self.thumbnail,'!= ',args)
        # print(kwargs)
        return super().save(*args, **kwargs)
        
    def get_display_price(self):
        
        for price in self.prices.all().filter(product=self):
            if price.active_price and price !=self:
                return price.price_amount/100                    
        return self.price /100
    
    
    def get_thumbnail(self):
        #print(self.thumbnail.url,' -------=====  ',self.thumbnail.field.upload_to)
        if self.thumbnail:
            origin= self.thumbnail.field.upload_to
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            else:
                return 'https://placehold.co/300x300/jpg'    
            
            
    def make_thumbnail(self, image, size=(300, 300)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)
        thumb_io = BytesIO()
        #check formats -> python -m PIL
        ext = valid_ext_dict.get(f".{image.name.split('.')[-1]}")
        
        img.save(thumb_io, ext, quality=85)
        name = image.name.replace('uploads/product_images/', '')
        thumbnail = File(thumb_io, name=name)

        return thumbnail
    

class CarouselImage(models.Model):
    product = models.ForeignKey('Product', related_name='carousel', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='carousel/')
    caption = models.CharField(max_length=100,blank=True)
    order = models.PositiveIntegerField()
    class Meta:
        ordering = ['order']

class Order(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    paid_amount = models.IntegerField(blank=True, null=True)
    is_paid = models.BooleanField(default=False)
    payment_intent = models.CharField(max_length=255)
    discount_code = models.CharField(max_length=35, null=True, blank=True)
    created_by = models.ForeignKey(User, related_name='orders', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    is_shipped = models.BooleanField(default=False)
    class Meta:
        ordering = ('-id','-created_at',)
        
    def get_display_price(self):
        return self.paid_amount /100
    
    def get_display_price_with_discount(self,user):
        if self.discount_code:
            discount,err = get_cupon(self.discount_code)
            tot_item = self.get_display_price_per_user(user)
            discount = (tot_item*100) * (discount.get('percent_off',0) /100)
            return tot_item-discount / 100
        else:
            return self.get_display_price_per_user(user)

    def __str__(self):
        return f'{self.id}'

    def get_display_price_per_user(self, user):
        total_price = self.items.filter(product__user=user).annotate(
            total_price=F('quantity') * F('price')
        ).aggregate(Sum('total_price'))['total_price__sum'] or 0
        return total_price / 100

    def get_total_quantity_per_user(self, user):
        return self.items.filter(product__user=user).aggregate(Sum('quantity'))['quantity__sum'] or 0



class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)
        
    def get_display_price(self):
        return self.price / 100
    
    def get_item_total(self):
        return (self.price/100)  * self.quantity
    
    def __str__(self) -> str:
        return f"Order: {self.order}, item:{self.product.title}"
    
    

class Product_Inventory(models.Model):
    product_id  = models.ForeignKey(Product, related_name='product_inv', on_delete=models.CASCADE)
    
    quantity    = models.IntegerField()
    created_at  = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateField(auto_now=True)
    #deleted_at = models.DateField(blank=True)
    # class Meta:        
    #     abstract =True

#this must be created with signal in orders
class Payment_Detail(models.Model):
    order_id    = models.ForeignKey(Order, related_name='payment_detail', on_delete=models.CASCADE)
    amount      = models.IntegerField()
    #provider can be another class with provider list or can be pyment type  
    provider    = models.CharField(max_length=35,blank=True)
    status      = models.CharField(max_length=10)
    created_at  = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateField(auto_now=True)

    # class Meta:
    #     abstract=True

store/forms.py
from django import forms
from . models import Product, Order, Discount, CarouselImage

class OrderForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput)
    class Meta:
        model= Order        
        fields = (
            'first_name', 
            'last_name', 
            'address', 
            'zipcode', 
            'city',
            'id',
            'discount_code',
        )







forma ='form-control'

class CarouselImageForm(forms.ModelForm):
    
    class Meta:
        model = CarouselImage
        fields=['image', 'caption']
        labels = {
            'image':'Extra image (optional)',
        }
        widgets={
            'image': forms.ClearableFileInput(attrs={
                'class': forma,
                'placeholder':'Image'
            }),
            'caption': forms.TextInput(attrs={
                'class': forma,
                'placeholder':'Caption (optional)',
            }),
            'order': forms.NumberInput(attrs={
                'class': forma,
                'min': 1
            }),
        }
    
    def save(self, product=None,commit=True):

        instance = super().save(commit=False)
        if product:
            # instance.product=product
            #instance.image=product.image
            print('instance', instance, '     product',product.image)
        instance.order = CarouselImage.objects.filter(product=self.instance.product_id).count() + 1
        
        if commit:
            instance.save()
        return instance

class ProductForm(forms.ModelForm):
    id_stripe =forms.CharField(widget=forms.HiddenInput, required=False)
    def __init__(self,*args, **kwargs):
        
        qs=kwargs.pop('qs',None)
        
        super(ProductForm,self).__init__(*args, **kwargs)
        
        if qs:            
            self.fields['discount']= forms.ModelChoiceField(required=False, queryset=qs,
            widget=forms.Select(attrs={
                
                'class': forma
            }))

    class Meta:
        model = Product
        fields = ('category', 'title', 'description', 'price', 'image', 'status','discount', 'id_stripe',)
        labels = {
            'image': 'Defualt image'
        }
        widgets = {
            'id_stripe':forms.TextInput(),
            'category': forms.Select(attrs={
                'class': forma,
                'placeholder':'Category'
            }),
            'title': forms.TextInput(attrs={
                'class': forma,
                'placeholder':'Title',
            }),
            'description': forms.Textarea(attrs={
                'rows':3,
                'class': forma,
                'placeholder':'Description',
            }),
            'price': forms.NumberInput(attrs={
                'class': forma,
                'pattern':'\d+',
                'placeholder':'Price'
            }),
           
            'image': forms.ClearableFileInput(attrs={
                'class': forma,
                'placeolder':'Image'
            }),
            'status': forms.Select(attrs={
                'class': forma,
                'placeholder':'Status'
            }),
            'discount': forms.Select(attrs={
                
                'class': forma,
            }),
            
        }

class DiscountForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    class Meta:
        model = Discount
        exclude = ('created_at','modified_at',)
        widgets= {
            
            'created_by':forms.HiddenInput(),
            'code_name': forms.TextInput(attrs={
                'class': forma,#'w-full mb-2 px-2 py-4 border border-gray-200'
            }),
            'desc': forms.Textarea(attrs={
                'rows':3,
                'class': forma,#'w-full mb-2 px-2 py-4 border border-gray-200'
            }),
            'stock': forms.NumberInput(attrs={
                'class': forma,#'w-full mb-2 px-2 py-4 border border-gray-200'
            }),
            'discount_percent': forms.NumberInput(attrs={
                'class': forma,#'w-full mb-2 px-2 py-4 border border-gray-200'
            }),
        }

store/templates/store/OrderForm.html
{% extends 'core/mainBase.html' %}

{% load widget_tweaks %}

{% block title %}Order Edit {% endblock title %}

{% block content %}
    <h1 class="mb-6 text-xl"> Order Edit {{orderId}} </h1>    
    {% if items  %}       
        {% for item in items  %}            
            <div class="border rounded px-4 py-4 mb-2" style="background-color: #007a74; color: #fff; display: flex; align-items: center;">
                <div>
                    <img src="{{item.product.get_thumbnail}}" class="w-20">
                </div>
                
                <div class="px-4 py-4 mb-2">
                    <h2 class="text-2xl">{{item.product.title}}</h2>
                    <p class="text-sm text-gray-500">Price: $ {{item.product.get_display_price}}</p>
                    <div class="mt-4 mb-4">
                        <a href="{% url 're_order_item' %}?oid={{orderId}}&item={{item.id}}&action=increase"class="px-4 py-2 border rounded text-white btn">
                            +
                        </a>
                        <span class="px-2 py-2">{{item.quantity}} </span>
                        
                        <button onclick="is_cero(event,'{{item.quantity}}', '{{item.id}}')" class="px-4 py-2 border rounded text-white btn">
                            - 
                        </button>
                        <a id="clickorderitem{{item.id}}" href="{% url 're_order_item' %}?oid={{orderId}}&item={{item.id}}&action=decrease">
                        </a>
                    </div>  
                    
                    <!--Delete btn-->
                    <button class="btn btn-danger mt-2" onclick="remove_reorder(event,'{{item.id}}', '{{item.quantity}}')" >
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                          </svg>
                        
                    </button>
                    <a id="clickorderitemRemove{{item.id}}" href="{% url 're_order_remove' %}?oid={{orderId}}&item={{item.id}}" class="inline-block">                        
                    </a>
                    <br>
                    <hr>
                    <span class="py-6 px-6 "> <strong> Item(s) total:</strong> ${{item.get_item_total}}  </span>
                </div>                
            </div>
            <hr>
            
            
        {% endfor %}        
        <span class="py-6 px-6 "> <strong> Order total:</strong> ${{order.get_display_price}} </span>
        <br>
        <span id="discount_span"></span>
        <br>
        <span id="discount_span_total"></span>
    {% endif %}
        
<div id="errors" class="hidden my-3 px-4 py-4 bg-red-200 rounded-xl"></div>
<div class="border rounded py-2 px-2">
    <form action="" method="post">    
        <div class="">
            <div class="mb-3">
                {% render_field form.first_name.label %}
                {% render_field form.first_name class+="form-control" %}
            </div>
    
            <div class="mb-3">
                {% render_field form.last_name.label %}
                {% render_field form.last_name class+="form-control" %}
            </div>
    
            <div class="mb-3">
                {% render_field form.address.label %}
                {% render_field form.address class+="form-control" %}
            </div>
    
            <div class="mb-3">
                {% render_field form.zipcode.label %}
                {% render_field form.zipcode class+="form-control" %}
            </div>
    
            <div class="mb-3">
                {% render_field form.city.label %}
                {% render_field form.city class+="form-control" %}
            </div>
            <div class="mb-3">
                {% render_field form.discount_code.label %}
                {% render_field form.discount_code class+="form-control" %}
                <label for="id_discount_code" id="label_alert"></label>
            </div>
            {% render_field form.id  %}
                
        </div> 
        <button type="submit" onclick="reOrder(event)" class="py-2 px-4 btn btn-success mb-4">Save</button> 
    </form>
</div>
{% endblock content%}

{% block scripts %}
<script type="application/javascript" src="https://js.stripe.com/v3/"></script>
<script>
    function remove_reorder(event,id, quantity){
        let si =confirm('Are you sure that you want to delete de item ?\n\n Note: if this is the only item in order, the order wil be deleted. ')
        
        if(!si){
            return
        }
        document.getElementById(`clickorderitemRemove${id}`).click() 
    }
    function is_cero(event,quantity,id){                
        if (quantity ==1){        
            let si =confirm('Are you sure that you want to delete de item and order ?')
            if(!si){
                return
            }            
        }
        document.getElementById(`clickorderitem${id}`).click()                
    }
    function validate(first_name, last_name, address, zipcode, city){
        let errors = [];

        if(first_name == ''){
            errors.push('The first name is missing.');
        }
        if(last_name == ''){            
            errors.push('The last name is missing.');
        }
        if(address == ''){            
            errors.push('The address is missing.');
        }
        if(zipcode == ''){            
            errors.push('The zipcode is missing.');
        }
        if(city == ''){            
            errors.push('The city is missing.');
        }
        
        let html =''
        
        for(let i =0; i < errors.length; i++){
            html += errors[i] + '<br>';
        }

        let errorElement = document.getElementById('errors');

        if(errors.length){
            errorElement.classList.remove('hidden');
            errorElement.innerHTML = html;
            return false;
        }else{
            errorElement.classList.add('hidden');
            return true;
        }
    }
    function reOrder(event){
        event.preventDefault()
        const first_name = document.getElementById('id_first_name').value;
        const last_name  = document.getElementById('id_last_name').value;
        const address    = document.getElementById('id_address').value;
        const zipcode    = document.getElementById('id_zipcode').value;
        const city       = document.getElementById('id_city').value;
        const oid        = document.getElementById('id_id').value;
        const discount_code = document.getElementById('id_discount_code').value;
        if(validate(first_name,last_name,address,zipcode,city) ){
            let data = {
                'first_name': first_name,
                'last_name' : last_name,
                'address'   : address,
                'zipcode'   : zipcode,
                'city'      : city,
                'id'       : oid,
                'discount_code': discount_code,
            }
            let stripe = Stripe('{{ pub_key }}')
            fetch(`{% url 're_order' %}`,{
                method: 'POST',
                headers:{
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{csrf_token}}'
                },
                credentials:'same-origin',
                body: JSON.stringify(data)
            })
            .then(function(response){
                console.log(response)
                return response.json()
            })
            .then(function(session){
                console.log(session)
                return stripe.redirectToCheckout({sessionId:session.session.id})
            })
            .then(function(result){
                console.log(result)
                //window.location.href=result.redirect
                if(result.error){
                    
                    location.reload()
                }
            })
            .catch(function(error){
                location.reload()
            });
        }
        return false
    }

    id_discount_code.addEventListener('keyup', (event)=>{
        check_code(event.target.value)
    })
    id_discount_code.addEventListener('keydown', (event)=>{
        check_code(event.target.value)
    })

    document.addEventListener('DOMContentLoaded', (event)=>{
        
        if (id_discount_code.value != ''){
            check_code(id_discount_code.value)
            
        }
    })
    function check_code(code_val){
        fetch(`{% url 'check_code_name' %}?code=${code_val}`,{
            method:'GET',
            headers:{
                'Content-Type': 'application/json',
                'X-Requested-With': 'XMLHttpRequest',                
            },
            credentials:"same-origin"
        })
        .then(response=>{
            return response.json()
        })
        .then(data=>{

            if(id_discount_code.value.length==0){
                label_alert.removeAttribute('style');
                label_alert.innerHTML="";
            }else{                
                
                if(data['res']==='valid'){
                    label_alert.innerHTML="Valid cupon!!!"
                    label_alert.setAttribute('style','border-radius: 15px; border:2px solid MediumSeaGreen;color:#ffffff; background-color:MediumSeaGreen;')
                    discount_span.innerHTML= `<strong>Discount:</strong> ${data['percent']} % OFF`
                    let total = parseFloat('{{order.paid_amount}}')
                    total =total/100
                    let dis = total * data['percent']/100
                    

                    discount_span_total.innerHTML = `<strong>Total with discount:</strong> ${total - dis}`
                }else{ 
                    label_alert.innerHTML="Invalid cupon, try another one"
                    label_alert.setAttribute('style','border-radius: 15px; border:2px solid Tomato;color:#ffffff; background-color:Tomato;')
                    discount_span.innerHTML=""
                    discount_span_total.innerHTML=""
                }
            }
            
        })
    }
</script>

{% endblock scripts %}

store/templates/store/category_detail.html
{% extends 'core/mainBase.html' %}


{% block title %} {{category.title}} {% endblock title %}



{% block content %}
    <h1 class="text-xl">{{category.title}}</h1>

    {% include 'store/partials/products.html' %} 
    
{% endblock content %}

store/templates/store/search.html
{% extends 'core/mainBase.html' %}


{% block title %}Search {% endblock title %}

{% block content %}
    <h1 class="text-xl"> Search </h1>
        
    {% if products %}
        <h2 class="text-xs text-gray-600"> Search results for "{{query}}":</h2>

        {% include 'store/partials/products.html' %} 
        
    {% else%}
        <p>There are no products match for "{{query}}" </p>
    {% endif %}
        

{% endblock content %}